# Generated by Django 5.1.4 on 2025-06-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_images',
        ),
    ]
